/**
 * OmniCore Model and State Management API
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@korewireless.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LogLevel.
* @enum {}
* @readonly
*/
export default class LogLevel {
    
        /**
         * value: "INFO"
         * @const
         */
        "INFO" = "INFO";

    
        /**
         * value: "ERROR"
         * @const
         */
        "ERROR" = "ERROR";

    

    /**
    * Returns a <code>LogLevel</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LogLevel} The enum <code>LogLevel</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

