/**
 * OmniCore Model and State Management API
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@korewireless.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PublicKeyCertificate from './PublicKeyCertificate';

/**
 * The RegistryCredential model module.
 * @module model/RegistryCredential
 * @version 1.0
 */
class RegistryCredential {
    /**
     * Constructs a new <code>RegistryCredential</code>.
     * @alias module:model/RegistryCredential
     */
    constructor() { 
        
        RegistryCredential.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegistryCredential</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegistryCredential} obj Optional instance to populate.
     * @return {module:model/RegistryCredential} The populated <code>RegistryCredential</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistryCredential();

            if (data.hasOwnProperty('publicKeyCertificate')) {
                obj['publicKeyCertificate'] = PublicKeyCertificate.constructFromObject(data['publicKeyCertificate']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegistryCredential</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegistryCredential</code>.
     */
    static validateJSON(data) {
        // validate the optional field `publicKeyCertificate`
        if (data['publicKeyCertificate']) { // data not null
          PublicKeyCertificate.validateJSON(data['publicKeyCertificate']);
        }

        return true;
    }


}



/**
 * @member {module:model/PublicKeyCertificate} publicKeyCertificate
 */
RegistryCredential.prototype['publicKeyCertificate'] = undefined;






export default RegistryCredential;

