/**
 * OmniCore Model and State Management API
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@korewireless.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RegistryCredential from './RegistryCredential';

/**
 * The RegistryCertificate model module.
 * @module model/RegistryCertificate
 * @version 1.0
 */
class RegistryCertificate {
    /**
     * Constructs a new <code>RegistryCertificate</code>.
     * @alias module:model/RegistryCertificate
     * @param credentials {module:model/RegistryCredential} 
     */
    constructor(credentials) { 
        
        RegistryCertificate.initialize(this, credentials);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, credentials) { 
        obj['credentials'] = credentials;
    }

    /**
     * Constructs a <code>RegistryCertificate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegistryCertificate} obj Optional instance to populate.
     * @return {module:model/RegistryCertificate} The populated <code>RegistryCertificate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistryCertificate();

            if (data.hasOwnProperty('credentials')) {
                obj['credentials'] = RegistryCredential.constructFromObject(data['credentials']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegistryCertificate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegistryCertificate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RegistryCertificate.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `credentials`
        if (data['credentials']) { // data not null
          RegistryCredential.validateJSON(data['credentials']);
        }

        return true;
    }


}

RegistryCertificate.RequiredProperties = ["credentials"];

/**
 * @member {module:model/RegistryCredential} credentials
 */
RegistryCertificate.prototype['credentials'] = undefined;






export default RegistryCertificate;

